application: groupquiz
version: 1
runtime: go
api_version: go1

#includes:
# - lib/daveIndex.go

handlers:
- url: /
  static_files: html/index.html
  upload: html/index.html
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /img
  static_dir: img
- url: /.*
  script: _go_app

